language: node_js
node_js:
- '4'
before_script:
- npm install -g bower
- bower install
deploy:
  provider: npm
  email: tomas.c.fox@gmail.com
  api_key:
    secure: fKVxr456XEPejKBkp++Z1VCWSpgLf0wC3lrOd296E9XRzP/9NYNRhiLDS8SYJkxPvRGLY2N0QeqXjLffy47DrbnZflMUuLn2uEEwTIZvV/aW6Fm88HMO0hRGeQc/SCTs66fDsELxbjxf+aNIl2c4CzYxOB6i0+dr8fmyaGQmOcLNERm/PHVNFxUMbYtghE4VV82sC/ZmroGAtfF8zyfEaHmJxwyu9agQlLQgOOBE5GiPwj8Ik9JRyxBEpyn64LNGAaJ+mMnZmLS1vZ8m1HTQ9PAFA/1XIMC73hOwJ/bnXg0J4NxGGzdT7bntvaDJuHd0+YYjJnp/xeQJcck27LkqhKlwvFTwvN1wZDtGVBWtjvchNFSYAJOjq7Jv9twSgimhN8QUG1/cNTwI/5vBHWzDJtCYczTmZi80cnhq8bVIhp4ejLOZb67sf1fXQw10Myy82za1pRBBkhxbWhsyq8EN7dPRGTxBTwIttZVP+mu9cHtDyAuXaSvQHPJuG6Bpg8QmHid0AFes/WsP3TAA3Bw7JCu8gFaYhOI6V5aUrYRXJYvhc1a5RbJb2uda4pimrztrGvDoyHlaw2myttEn2srrXtE47/HiDrS3gvzF73uYgQTEouDhrNDayvggwPTnv0Xfvd6AX3ZBW8d5Y1hNKx2PB6n7huc/npHlQun7+k70Glk=
  on:
    tags: true
    repo: tfoxy/bs-injular
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage-merged/lcov.info